### ISSUE TITLE
Append new notices.

### ISSUE THREAD

**Issue by juma-h** [noticebord/noticebord#11]
### Suggestion....? @sixpeteunder 

- Can we make it so that newly saved notices are at the top of the page, just before the numbered 'faux' notices made?
- One has to go through almost 2+ _**load more**_  to get the user saved notices  - from browser extension.

**Comment by sixpeteunder** [comment]
Yes, I can do that.

**Comment by juma-h** [comment]
Thank you bb

**Comment by peter-mghendi** [comment]
Done
